### PR TITLE
Fixed the grammer issue

### LINKED ISSUE #21: Sushi-Zen introduction paragraph has too many exclamation marks
As a user, I should only see one exclamation mark (`!`) in the introduction/description paragraph.

> This Sushi Recipe will show you how to make sushi like a pro!!!!

## Reproduction Steps
1. Navigate to recipes.brannan.cloud/japanese/sushi
2. Observe there are too many exclamation marks.

### PR DESCRIPTION
**Pull request by Chubbar5**
Fixes #21

### CODE REVIEW

**Review by bananabrann — CHANGES_REQUESTED** [review]
Changes look good

In your PR's description, [use one of these keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to create the proper link between the issue and this PR

**Comment by Chubbar5** [comment]
#21 fixed

**Review by bananabrann — APPROVED** [review]

**Comment by bananabrann** [comment]
@Chubbar5 **_squash_** merge at your convenience

**Comment by bananabrann** [comment]
@Chubbar5 delete your branch please

**Pull request merged**
